# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - cmake
    - dbus
    - libcairo-dev
    - libdbus-1-dev
    - libpython3-dev
    - libdbus-glib-1-dev
    - libgirepository1.0-dev
    - gir1.2-gtk-3.0
    - gir1.2-gtksource-3.0
    - gir1.2-appindicator3-0.1
    - gir1.2-glib-2.0
    - gir1.2-notify-0.7
    - python3-dbus
    - python3-gi
    - python3-pyudev
    - pyqt5-dev-tools

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: readthedocs/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: readthedocs/requirements.txt
        
