#!/usr/bin/env python3

#  For standalone testing
import json

import dbus
import dbus.service
import dbus.mainloop.glib
from gi.repository import GLib
import os
import subprocess
import tempfile
import threading
import time

#  For standalone testing
import logging
logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s', datefmt='%d-%b-%y %H:%M:%S', level=logging.DEBUG)
logger = logging.getLogger(__name__)

#  This is how we talk to Kwin.  We write a KWin script, we send that to
#  KWin over DBus.  KWin responds with a return code but no output.  To
#  receive any data back from a KWin script we put a call in the script
#  to have it send the data we wanted back to us via a dbus service we
#  set up to listen for a message from KWin.

#  Define the Kwin listening service.
DBUS_SERVICE_NAME='com.autokey.KwinListener'

class KWinListener(dbus.service.Object):
    """
    Create a DBus service that listens for one message, returns the
    content of that message, and then quits.

    :keyword timeout_seconds: how long, in seconds, the service should
    wait to receive a message before it quits, returning nothing.
    Default is 5 seconds.
   :type timeout_seconds: integer
    """
    def __init__(self, timeout_seconds=5):
        self._result = ''
        self._timeout_seconds = timeout_seconds
        self._service_name = DBUS_SERVICE_NAME
        self._service_path = '/' + self._service_name.replace('.', '/')

    def run(self):
        """
        Start the dbus service, wait for a message, and return the
        content.

        :return: the contents of the dbus message that was received, if
        any.
        :rtype: string
        """
        dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
        bus_name = dbus.service.BusName(self._service_name, dbus.SessionBus())
        dbus.service.Object.__init__(self, bus_name, self._service_path)
        GLib.timeout_add_seconds(self._timeout_seconds, self._timeout)
        self._loop = GLib.MainLoop()
        logger.debug('KWinListener dbus service is ready to receive messages')
        self._loop.run()
        return self._result

    def _timeout(self):
        """
        This method is called to terminate the service when it times out,
        """
        logger.debug('KWinListener timed out waiting for a message')
        self._loop.quit()

    @dbus.service.method(dbus_interface=DBUS_SERVICE_NAME, in_signature='s', out_signature='')
    def Response(self, result):
        """
        This is the dbus service's sole method.

        :param result: The contents of the message that was received from
        the client, if any.
        :type result: string
        """
        self._loop.quit()
        self._result = result

class KWinInterface():

    #  Send the script to Kwin's dbus service, run it, and delete it
    @staticmethod
    def __send_kwin_script(script, service_name, response_expected=False):
        """
        Loads a KWin script and executes it.  If a response is expected
        to come back from the script via a bdus message, a KWinListener
        dbus service is used to collect that response.

        :param script: The KWin script's code
        :type script: string
        :param service_name: The name of the KwinListener dbus service
        :type service_name: string
        :keyword response_expected: Flag indicating whether or not a
        KWinListener service needs to be set up to collect data from the
        KWin script when it runs.
        :type response_expected: boolean
        """
        #  Write the script into a temporary file
        (f, fn) = tempfile.mkstemp(prefix='autokey.kwin.script', suffix='.js')
        with open(fn, 'w') as script_file:
            script_file.write(script)
        logger.debug(f'KWin script filename: {fn}')

        #  Load the script
        try:
            proc = subprocess.run(['dbus-send', '--print-reply', '--dest=org.kde.KWin', '/Scripting', 'org.kde.kwin.Scripting.loadScript', f'string:{fn}'], capture_output=True, check=True)
            logger.debug(proc)
        except subprocess.CalledProcessError:
            logger.exception('Unexpected exception loading a KWin script')
            return
        script_id = proc.stdout.decode('utf-8').split('\n')[1].strip().split(' ')[1]
        if not script_id:
            try:
                script_id = print(proc.stdout.split('\n')[1].strip().split(' ')[1])
            except TypeError:
                pass
            if not script_id:
                logger.error('KWin script loaded, but I could not get the script_id')
                try:
                    proc = subprocess.run(['dbus-send', '--print-reply', '--dest=org.kde.KWin', '/Scripting', 'org.kde.kwin.Scripting.unloadScript', f'string:{fn}'], capture_output=True, check=True)
                    logger.debug(proc)
                except subprocess.CalledProcessError:
                    logger.exception('Unexpected exception loading a KWin script')
                return

        logger.debug(f'KWin script id number: {script_id}')

        #  Wait for the listener to come up, but only if we're expecting a response
        if response_expected:
            #  Wait for KWinListener service to appear
            found = False
            while not found:
                proc = subprocess.run(['dbus-send', '--session', '--print-reply', '--dest=' + service_name, '/' + service_name.replace('.', '/'), 'org.freedesktop.DBus.Introspectable.Introspect'], capture_output=True, check=True)
                if proc.returncode == 0:
                    found=True
                time.sleep(0.1)

        #  Execute the script
        try:
            proc = subprocess.run(['dbus-send', '--print-reply', '--dest=org.kde.KWin', f'/Scripting/Script{script_id}', 'org.kde.kwin.Script.run'], capture_output=True, check=True)
            logger.debug(proc)
        except subprocess.CalledProcessError:
            logger.exception('Unexpected exception running a KWin script')
            return

        #  Unload the script and erase the script file
        try:
            proc = subprocess.run(['dbus-send', '--print-reply', '--dest=org.kde.KWin', '/Scripting', 'org.kde.kwin.Scripting.unloadScript', f'string:{fn}'], capture_output=True, check=True)
            logger.debug(proc)
            os.unlink(fn)
        except subprocess.CalledProcessError:
            logger.exception('Unexpected exception running a KWin script')
            return

    #  This function is the entrypoint for all of the above ...
    def run_kwin_script(script, response_expected=False):
        """
        This the entrypoint into the KWin interface.  Call this method
        to execute a KWin script and retrieve the results, if any.

        :param script: The KWin script's code
        :type script: string
        :keyword response_expected: Flag indicating whether or not data
        is expected to be returned.
        :type response_expected: boolean
        """
        if response_expected:
            #  Append the callDBus to the end of the script.  Make sure script
            #  has put the data it wants to send into the "result" variable.
            script = script + f'\ncallDBus("{DBUS_SERVICE_NAME}", "{'/' + DBUS_SERVICE_NAME.replace('.', '/')}", "{DBUS_SERVICE_NAME}", "Response", result)'
            #  Send the script to Kwin using a separate thread
            t = threading.Thread(target=KWinInterface.__send_kwin_script, args=(script, DBUS_SERVICE_NAME,), kwargs={'response_expected': response_expected})
            t.start()
            #  Start our dbus listener
            result = KWinListener().run()
            t.join()
            return result
        else:
            #  Send the script without waiting for anything back
            KWinInterface.__send_kwin_script(script, DBUS_SERVICE_NAME)

#  Testing:
#
#  Make a call to get a bunch of data on the windows on the desktop
kwin_script = """const windows = workspace.windowList();
winJsonArr = [];
windows.forEach(function(w) {
    if ((!w.desktopWindow) && ((w.desktops).length > 0)) {
        winJsonArr.push({
            wm_class: w.resourceClass,
            wm_class_instance: null,
            wm_title: w.caption,
            workspace: w.desktops[0].x11DesktopNumber,
            desktop: w.desktops[0].id,
            pid: w.pid,
            id: w.internalId,
            frame_type: null,
            window_type: w.windowType,
            width: w.width,
            height: w.height,
            x: w.x,
            y: w.y,
            focus: w.active,
            in_current_workspace: null
        });
    }
});
result = JSON.stringify(winJsonArr, null, 0);"""
result = KWinInterface.run_kwin_script(kwin_script, response_expected=True)
logger.debug(json.dumps(json.loads(result), indent=4))
