#!/usr/bin/env python3

from gi.repository import GLib
from pydbus import SessionBus
import tempfile
import threading
import time

class KWinListener(object):
    """
        <node>
            <interface name='org.autokey.kwinlistener'>
                <method name='Response'>
                    <arg type='s' name='response' direction='in'/>
                </method>
            </interface>
        </node>
    """

    def Response(self, message):
        print(message)
        loop.quit()

    def _timeout():
        print('timed out')
        loop.quit()

def run_script(response_expected=False):

    kwin_script="""const w = workspace.activeScreen.geometry;
result = [w.width, w.height];
result = JSON.stringify(result, null, 4);"""

    bus = SessionBus()

    if response_expected:
        time.sleep(120)
        kwin_script = kwin_script + f'\ncallDBus("org.autokey.kwinlistener", "/org/autokey/kwinlistener", "org.autokey.kwinlistener", "Response", result)'
        print(kwin_script)

        #  Wait for KWinListener service to appear
        found = False
        while not found:
            try:
                obj = bus.get('org.autokey.kwinlistener')
                result = obj.Introspect()
                found = True
            except Exception as e:
                time.sleep(0.1)

    (f, fn) = tempfile.mkstemp(prefix='autokey.kwin.script', suffix='.js')
    with open(fn, 'w') as script_file:
        script_file.write(kwin_script)

    obj = bus.get('org.kde.KWin', '/Scripting')
    script_id = str(obj.loadScript(fn))
    print(f'loading = {script_id}')

    obj = bus.get('org.kde.KWin', f'/Scripting/Script{script_id}')
    result = obj.run()
    print(f'running = {result}')

    obj = bus.get('org.kde.KWin', '/Scripting')
    result = obj.unloadScript(fn)
    print(f'unloading = {result}')

response_expected = True
t = threading.Thread(target=run_script, kwargs={'response_expected': response_expected})
t.start()

loop = GLib.MainLoop()
bus = SessionBus()
bus.publish('org.autokey.kwinlistener', KWinListener())
GLib.timeout_add_seconds(5, KWinListener._timeout)
loop.run

t.join()

