#!/usr/bin/env python3

from gi.repository import GLib
from pydbus import SessionBus
from pydbus import SystemBus
import random
import threading
import time
import subprocess

class KWinListener(object):
  """
    <node>
      <interface name='org.autokey.listener'>
        <method name='Response'>
          <arg type='s' name='message' direction='in'/>
        </method>
      </interface>
    </node>
  """

  def Response(self, message):
      print(message)
      loop.quit()

class KWinInterface():

    def __init__(self):
        pass

    def _send_script_thread(self, script, subdir):
        time.sleep(5)
        proc = subprocess.run(f'dbus-send --print-reply --dest=org.autokey.listener /org/autokey/listener/{subdir} org.autokey.listener.Response string:"{script}"', shell=True, check=True)

    def send_script(self, script):

        subdir = str(random.randint(0, 99999999))
        print(subdir)

        t = threading.Thread(target=self._send_script_thread, args=(script, subdir,))
        t.start()

        loop = GLib.MainLoop()
        bus = SessionBus()
        bus.publish('org.autokey.listener', (subdir, KWinListener()))
        loop.run

        t.join()

kwin = KWinInterface()
result = kwin.send_script('Hello world')
print(result)


