name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: []
projects: []
assignees:
  - dlk3
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: What Linux distribution did you run AutoKey on?  Please include the version number.
      placeholder: ex. Fedora 41
    validations:
      required: false
  - type: input
    id: desktop
    attributes:
      label: Desktop Environment
      description: What desktop environment was AutoKey running in?
      placeholder: ex. Gnome
    validations:
      required: false
  - type: dropdown
    id: windowmgr
    attributes:
      label: Window Manager
      description: What window manager was in use at the time?
      options:
        - X11
        - Wayland
        - Other
      default: 0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen?
      placeholder: Tell us what you saw!
    validations:
      required: true
  - type: markdown
    attributes:
      value: If applicable, please follow the instructions in [the documentation](https://autokey-wayland.readthedocs.io/en/latest/troubleshoot/issues.html) and create a debug log that captures the bug, and attach that to this bug report.
