name: Other Type Of Issue
description: Create a new, non-bug, issue like a new feature request.
title: "[Other]: "
labels: []
projects: []
assignees:
  - dlk3
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Add a description
      placeholder: Type your description here...
    validations:
      required: true
