name: Bug Report
description: File a bug report.
title: ""
labels: ["bug","triage"]
projects: ["dlk3/autokey-wayland"]
assignees:
  - dlk3
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Please read the [FAQ](https://github.com/dlk3/autokey-wayland/wiki/FAQ-%E2%80%90-Frequently-Asked-Questions) before submitting a bug report
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: What happened? What did you expect to happen? What environment are you running AutoKey in?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Attach a debugging log
      description: Drag and drop your autokey.log file here
      render: shell
