name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: []
projects: []
assignees:
  - dlk3
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: What Linux distribution did you run AutoKey on?  Please include the version number.
      placeholder: ex. Fedora 41
    validations:
      required: false
  - type: input
    id: desktop
    attributes:
      label: Desktop Environment
      description: What desktop environment was AutoKey running in?
      placeholder: ex. Gnome
    validations:
      required: false
  - type: dropdown
    id: windowmgr
    attributes:
      label: Window Manager
      description: What window manager was in use at the time?
      options:
        - X11
        - Wayland
        - Other
      default: 0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: If applicable, please follow the intructions in [this entry](https://github.com/dlk3/autokey-wayland/wiki/FAQ-%E2%80%90-Frequently-Asked-Questions#attaching-an-autokey-debug-log-to-a-problem-issues-report) in the FAQ to create a debug log that captures this bug, and attach it to this bug report.
