#!/bin/sh

case "$1" in
    remove|deconfigure)
	if [ "$(logname)" != "root" ]; then
            usermod -r -G "input" "$(logname)"
	    su -c 'gnome-extensions uninstall "autokey-gnome-extension@autokey"' $(logname)
	fi

        rm -f '/etc/udev/rules.d/10-autokey.rules'
        /usr/bin/udevadm control --reload
	/usr/bin/udevadm trigger --sysname-match='/devices/virtual/misc/uinput'
    ;;
esac

#DEBHELPER#

exit 0
