#!/usr/bin/env bash

#  Copyright (C) 2026  David King <dave@daveking.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License,
#  version 2, as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License,
#  version 2, along with this program; if not, see
#  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
 #####################################################################

#  Generate the Ubuntu debs for AutoKey using a Ubuntu container

#  Source code to build and version number to use
GIT_URL='https://github.com/dlk3/autokey-wayland.git'
VERSION='v0.97.5'

#  Location of the default (testing) PPA:
PPA_DIR='daveking.com:/opt/autokey-wayland-ppa-testing'

#  Specify the default for the branch that is to be built.
#  Can be overidden by an environment variable when this script is called
#  inside a container
if [ -z "$BRANCH_OPTS" ]; then
    BRANCH_OPTS="--branch develop --single-branch"
fi

#  Tag of the docker.io Ubuntu container we use as the base for our container build
UBUNTU_CONTAINER="ubuntu:latest"

#  Debian build tools need an email address for the maintainer
export DEBEMAIL='dave@daveking.com'

#  Handle command line options
usage () {
    echo "Usage: $0 [-d] [-h] [-p]"
    echo "    where:"
    echo "        -d : keep container open for debugging when there is an error"
    echo "        -p : Publish the results to the production PPA.  The default is"
    echo "             to publish to the test PPA."
}

#  Specify the default for the -d option
#  Can be overidden by an environment variable when this script is called
#  inside a container
if [ -z "$DEBUG" ]; then
    DEBUG=false
fi
while getopts "dph" OPT; do
    case "${OPT}" in
	d)
	    DEBUG=true
	    ;;
        p)
            BRANCH_OPTS="--branch main --single-branch"
            PPA_DIR='daveking.com:/opt/autokey-wayland-ppa'
            ;;
        h)
            usage
            exit
            ;;
        *)
            echo "Invalid option: $OPT"
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

#  Abend the script when something bad happens.  Will execute the ERR trap
#  if/when one is in force (see below)
set -e

if [ ! $container ]; then

    #  This section of the script does not run in the podman container, it only
    #  runs on my workstation and drives the overall build process
    cd $(dirname $(realpath "$0"))

        #  Run any tests
    pytest ..
    RC=$?
    if [ $RC != 0 ]; then
        exit $RC
    fi

    #  Build the debs in a container
    echo "Starting build at $(date +%H:%m:%S)"
    OPT=""
    if $DEBUG; then
        OPT="-it"
    fi
    /usr/bin/podman run $OPT --name=debbuild --rm --volume=${HOME}:${HOME} --env="BRANCH_OPTS=$BRANCH_OPTS" --env="DEBUG=$DEBUG" docker.io/${UBUNTU_CONTAINER} "$(realpath "$0")" ${HOME}

    echo "Build complete at $(date +%H:%m:%S)"

    #  Put the deb files into my PPA
    ./update_ppa "$PPA_DIR"

else

    #  This section of the script runs in the docker container to build the Ubuntu
    #  debs.

    #  The output packages will be copied to the $HOME/Downloads directory of
    #  the user running this script.
    TARGETDIR=$1

        #  Keep the container running and give me a shell prompt when something bad happens
    if $DEBUG; then
        trap /bin/sh ERR
    fi

    apt update -y
    apt upgrade -y
    apt install -y git sudo zip python3-pytest

    mkdir -p ${HOME}/src
    cd ${HOME}/src

    echo git clone $BRANCH_OPTS "$GIT_URL"
    git clone $BRANCH_OPTS "$GIT_URL"
    cd autokey-wayland
    git tag -f "$VERSION"
    pytest
    debian/build.sh

    #  Copy the package files out of the container and on to the host
    cp -vr ${HOME}/src/*.deb ${TARGETDIR}/Downloads/

fi
