#!/usr/bin/env bash

#  Generate the Ubuntu debs for AutoKey using a Ubuntu 24.04 LTS container

#  Source code to build and version number to use 
GIT_URL='https://github.com/dlk3/autokey-wayland.git'
BRANCH='new-install'
VERSION='v0.97.1'

#  Location we rsync the PPA updates to:
PPA_DIR='daveking.com:/opt/autokey-wayland-ppa/'

#  Tag of the docker.io Ubuntu container we use as the base for our container build
UBUNTU_CONTAINER="ubuntu:latest"

#  Debian build tools need an email address for the maintainer
export DEBEMAIL='dave@daveking.com'

#  Handle command line options
usage () {
	echo "Usage: $0 [-d] [-h] [-t]"
	echo "    where:"
	echo "        -d : keep container open for debugging when there is  an error"
	echo "        -t : test build, do not publish the results to the PPA"
}

DEBUG=false
TESTBUILD=false
while getopts "dth" OPT; do
	case "${OPT}" in
		d)
			DEBUG=true
			;;
		t)
			TESTBUILD=true
			;;
		h)
			usage
			exit
			;;
		*)
			echo "Invalid option: $OPT"
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))
	
#  Abend the script when something bad happens.  Will execute the ERR trap 
#  if/when one is in force (see below)
set -e

if [ ! $container ]; then

	#  This section of the script does not run in the podman container, it only
	#  runs on my workstation and drives the overall build process
	cd $(dirname $(realpath "$0"))

	#  Build the debs in a container
	echo "Starting build at $(date +%H:%m:%S)"
	OPT=""
	if $DEBUG; then
		OPT="-it"
	fi
	/usr/bin/podman run $OPT --name=debbuild --rm --volume=${HOME}:${HOME} docker.io/${UBUNTU_CONTAINER} "$(realpath "$0")" ${HOME}
	echo "Build complete at $(date +%H:%m:%S)"
		
	#  If this isn't a test, put the deb files into my PPA
	if [ $TESTBUILD == false ]; then
	
		#  Update PPA
		rm -fr /tmp/ppa &>/dev/null || true
		rsync --archive --partial --progress $PPA_DIR /tmp/ppa/
		mv ${HOME}/Downloads/autokey*.deb /tmp/ppa/
		cd /tmp/ppa

		#  Keep only one version of each package
		PREV_NAME=""
		PREV_VERSION=""
		for f in $(ls -r *.deb); do
			NAME=$(echo "$f" | cut -f1 -d_)
			VERSION=$(echo "$f" | cut -f2 -d_)
			VERSION=${VERSION%.*}
			if [ "$NAME" == "$PREV_NAME" ] && [ "$VERSION" == "$PREV_VERSION" ]; then
				echo "$(date "$DATEFMT"): Deleting $f"
				rm "$f" &>/dev/null || true
			else
				PREV_NAME="$NAME"
				PREV_VERSION="$VERSION"
			fi
		done

		#  Create the Packages files in the repo
		echo "Creating Packages files for PPA"
		dpkg-scanpackages --multiversion . >Packages
		gzip -k -f Packages
	    
		# Create the Release files in the repo
		echo "Creating Release files for PPA"
		
		do_hash() {
			HASH_NAME=$1
			HASH_CMD=$2
			echo "${HASH_NAME}:"
			for f in $(find -type f); do
				f=$(echo $f | cut -c3-) # remove ./ prefix
				if [[ $f == Release* ]] || [[ $f == InRelease* ]] || [[ $f == index.html ]] || [[ $f == markdown.css ]] || [[ $f == pgp-key.public ]]; then
					continue
				fi
				echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
			done
		}

		cat << EOF > Release
Origin: autokey-wayland Repository
Label: autokey-wayland
Suite: unstable
Codename: unstable
Version: 1.0
Architectures: all
Components: main
Description: AutoKey for Wayland
Date: $(date -Ru)
EOF
		do_hash "MD5Sum" "md5sum" >> Release
		do_hash "SHA1" "sha1sum" >> Release
		do_hash "SHA256" "sha256sum" >> Release

		#  Sign the Release file
		echo "Signing the Release file"
		export GNUPGHOME=${HOME}/.gnupg-ppakey
		cat Release | gpg -abs >Release.gpg
		cat Release | gpg -abs --clearsign >InRelease

		echo "Sync local repo with remote web site"
		rsync --archive --partial --progress --delete /tmp/ppa/ "$PPA_DIR"
		echo "Sync complete"
	fi

else

	#  This section of the script runs in the docker container to build the Ubuntu
	#  debs.

	#  The output packages will be copied to the $HOME/Downloads directory of
	#  the user running this script.
	TARGETDIR=$1

        #  Keep the container running and give me a shell prompt when something bad happens
	if $DEBUG; then
		trap /bin/sh ERR
	fi

	apt update -y
	apt upgrade -y
	apt install -y git sudo zip

	#  Create the rpmbuild directory tree inside the container
	mkdir -p ${HOME}/src
	cd ${HOME}/src

	BRANCH_OPTS=""
	if [ -n "$BRANCH" ] && [ "$BRANCH" != "main" ]; then
		BRANCH_OPTS="--branch $BRANCH --single-branch"
	fi
	echo git clone $BRANCH_OPTS "$GIT_URL"
	git clone $BRANCH_OPTS "$GIT_URL"
	cd autokey-wayland
	git tag "$VERSION"
	debian/build.sh
	
	#  Copy the package files out of the container and on to the host
	cp -vr ${HOME}/src/*.deb ${TARGETDIR}/Downloads/
	
fi
