#!/usr/bin/env bash

#  Copyright (C) 2026  David King <dave@daveking.com>
#  
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License,
#  version 2, as published by the Free Software Foundation.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License,
#  version 2, along with this program; if not, see 
#  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
 #####################################################################

#  Update PPA with debs found in Downloads folder (from mkpackage -t)

#  Location we rsync the PPA updates to:
PPA_DIR='daveking.com:/opt/autokey-wayland-ppa/'

#  Handle command line options
usage () {
	echo "Usage: $0 [-h]"
}

DEBUG=false
TESTBUILD=false
while getopts "dth" OPT; do
	case "${OPT}" in
		h)
			usage
			exit
			;;
		*)
			echo "Invalid option: $OPT"
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))
	
#  Abend the script when something bad happens.  Will execute the ERR trap 
#  if/when one is in force (see below)
set -e

#  Update PPA
rm -fr /tmp/ppa &>/dev/null || true
rsync --archive --partial --progress $PPA_DIR /tmp/ppa/
mv ${HOME}/Downloads/autokey*.deb /tmp/ppa/
cd /tmp/ppa

#  Keep, at most, $LIMIT versions of each package
LIMIT=3
OLD_NAME=''
CTR=0
for PKG in $(ls *.deb | sort -r); do
        PKG_NAME=$(echo $PKG | cut -d_ -f1)
        if [ "$PKG_NAME" != "$OLD_NAME" ]; then
                CTR=1
                OLD_NAME=$PKG_NAME
        else
                CTR=$(( $CTR + 1 ))
        fi
        if [[ $CTR > $LIMIT ]]; then
                rm $PKG
        fi
done	

#  Create the Packages files in the repo
echo "Creating Packages files for PPA"
dpkg-scanpackages --multiversion . >Packages
gzip -k -f Packages

# Create the Release files in the repo
echo "Creating Release files for PPA"

do_hash() {
	HASH_NAME=$1
	HASH_CMD=$2
	echo "${HASH_NAME}:"
	for f in $(find -type f); do
		f=$(echo $f | cut -c3-) # remove ./ prefix
		if [[ $f == Release* ]] || [[ $f == InRelease* ]] || [[ $f == index.html ]] || [[ $f == markdown.css ]] || [[ $f == pgp-key.public ]]; then
			continue
		fi
		echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
	done
}

cat << EOF > Release
Origin: autokey-wayland Repository
Label: autokey-wayland
Suite: unstable
Codename: unstable
Version: 1.0
Architectures: all
Components: main
Description: AutoKey for Wayland
Date: $(date -Ru)
EOF
do_hash "MD5Sum" "md5sum" >> Release
do_hash "SHA1" "sha1sum" >> Release
do_hash "SHA256" "sha256sum" >> Release

#  Sign the Release file
echo "Signing the Release file"
export GNUPGHOME=${HOME}/.gnupg-ppakey
cat Release | gpg -abs >Release.gpg
cat Release | gpg -abs --clearsign >InRelease

echo "Sync local repo with remote web site"
rsync --archive --partial --progress --delete /tmp/ppa/ "$PPA_DIR"
echo "Sync complete"
