#!/usr/bin/env python3

import subprocess
import time

import sys
sys.path.append('/home/dlk/src/autokey-wayland/lib')

import logging
logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s', datefmt='%d-%b-%y %H:%M:%S', level=logging.DEBUG)
logger = logging.getLogger(__name__)

import os
if os.environ['XDG_CURRENT_DESKTOP'] =="KDE":
    from kde_window_interface import KdeWindowInterface
    from kde_mouse_interface import KdeMouseInterface
    mouse = KdeMouseInterface()
    mediator = KdeWindowInterface()
else:
    from gnome_interface import GnomeExtensionWindowInterface
    from gnome_interface import GnomeMouseReadInterface
    mouse = GnomeMouseReadInterface()
    mediator = GnomeExtensionWindowInterface()

result = mouse.mouse_location()
print(f'mouse_location() = {result}\n')

result = mediator.get_window_info()
print(f'get_window_info() = {result}\n')

mediator.cancel()
mouse.cancel()
exit()

window_list = mediator.get_window_list()
print(f'get_window_list() = {window_list}\n')

result = mediator.get_window_title()
print(f'get_window_title() = {result}\n')

result = mediator.get_window_class()
print(f'get_window_class() = {result}\n')

result = mediator.get_screen_size()
print(f'get_screen_size() = {result}\n')

# window API functions

result = mediator.get_active_window()
print(f'get_active_window() = {result}\n')

result = mediator.get_active_desktop_index()
print(f'get_active_desktop_index() = {result}\n')

print('Opening a KSuduko window, so that I can test close_window(id)')
subprocess.run('ksudoku &', shell=True)
time.sleep(1)
window_list = mediator.get_window_list()
for window in window_list:
    if 'KSudoku' in window['wm_title']:
        mediator.close_window(window['id'])
print()

print('activate_window()')
for window in window_list:
    if not window['focus'] and 'X Recording bridge' not in window['wm_title']:
        print(f'\tActivating {window['wm_title']}')
        mediator.activate_window(window['id'])
        break
print()

print('move_resize_window()\n')
window = mediator.get_active_window()
mediator.move_resize_window(window['id'], 100, 100, 1000, 1000)
time.sleep(1)
mediator.move_resize_window(window['id'], window['x'], window['y'], window['width'], window['height'])

print('move_to_workspace() and switch_workspace()\n')
window = mediator.get_active_window()
mediator.move_to_workspace(window['id'], 1)
time.sleep(1)
mediator.switch_workspace(1)
time.sleep(1)
mediator.move_to_workspace(window['id'], 0)
time.sleep(1)
mediator.switch_workspace(0)
time.sleep(1)

print('get_properties()')
window = mediator.get_active_window()
print(mediator.get_properties(window['id']), '\n')

print('maximize_window()/unmaximize_window()  horizontally')
window = mediator.get_active_window()
mediator.activate_window(window['id'])
mediator.maximize_window(window['id'], 1)
time.sleep(1)
mediator.unmaximize_window(window['id'], 1)
time.sleep(1)
print('maximize_window()/unmaximize_window()  vertically')
mediator.maximize_window(window['id'], 2)
time.sleep(1)
mediator.unmaximize_window(window['id'], 2)
time.sleep(1)
print('maximize_window()/unmaximize_window()  both\n')
mediator.maximize_window(window['id'], 3)
time.sleep(1)
mediator.unmaximize_window(window['id'], 3)
time.sleep(1)

print('make_fullscreen_window()/unmake_fullscreen_window()\n')
mediator.make_fullscreen_window(window['id'])
time.sleep(1)
mediator.unmake_fullscreen_window(window['id'])
time.sleep(1)

print('make_above_window()/unmake_above_window() (no visual effect)\n')
mediator.make_above_window(window['id'])
time.sleep(1)
mediator.unmake_above_window(window['id'])
time.sleep(1)

mediator.cancel()
mouse.cancel()
