#!/usr/bin/env python3

import sys
sys.path.append('/home/dlk/src/autokey-wayland/lib')

import os
if os.environ['XDG_CURRENT_DESKTOP'] =="KDE":
    from kde_interface import KdeWindowInterface
    from kde_interface import KdeMouseReadInterface
    mouse = KdeMouseReadInterface()
    mediator = KdeWindowInterface()
else:
    from gnome_interface import GnomeExtensionWindowInterface
    from gnome_interface import GnomeMouseReadInterface
    mouse = GnomeMouseReadInterface()
    mediator = GnomeExtensionWindowInterface()

result = mediator.get_window_list()
print(f'get_window_list = {result}\n')

result = mediator.get_window_info()
print(f'get_window_info = {result}\n')

result = mediator.get_window_title()
print(f'get_window_title = {result}\n')

result = mediator.get_window_class()
print(f'get_window_class = {result}\n')

result = mediator.get_screen_size()
print(f'get_screen_size = {result}\n')

result = mouse.mouse_location()
print(f'mouse_location = {result}\n')
