#!/usr/bin/env python3

import sys
sys.path.append('/home/dlk/src/autokey-wayland/lib')

from kde_interface import KdeWindowInterface

mediator = KdeWindowInterface();

result = mediator.get_window_list()
print(f'get_window_list = {result}\n')

result = mediator.get_window_info()
print(f'get_window_info = {result}\n')

result = mediator.get_window_title()
print(f'get_window_title = {result}\n')

result = mediator.get_window_class()
print(f'get_window_class = {result}\n')
